# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fen2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fen2(object):
    def setupUi(self, Fen2):
        Fen2.setObjectName("Fen2")
        Fen2.resize(371, 183)
        self.buttonBox = QtWidgets.QDialogButtonBox(Fen2)
        self.buttonBox.setGeometry(QtCore.QRect(10, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.labelNom = QtWidgets.QLabel(Fen2)
        self.labelNom.setGeometry(QtCore.QRect(20, 10, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelNom.setFont(font)
        self.labelNom.setObjectName("labelNom")

        self.retranslateUi(Fen2)
        self.buttonBox.accepted.connect(Fen2.accept)
        self.buttonBox.rejected.connect(Fen2.reject)
        QtCore.QMetaObject.connectSlotsByName(Fen2)

    def retranslateUi(self, Fen2):
        _translate = QtCore.QCoreApplication.translate
        Fen2.setWindowTitle(_translate("Fen2", "Dialog"))
        self.labelNom.setText(_translate("Fen2", "Usager"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fen2 = QtWidgets.QDialog()
    ui = Ui_Fen2()
    ui.setupUi(Fen2)
    Fen2.show()
    sys.exit(app.exec_())
