# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fen1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fen1(object):
    def setupUi(self, Fen1):
        Fen1.setObjectName("Fen1")
        Fen1.resize(371, 183)
        self.buttonBox = QtWidgets.QDialogButtonBox(Fen1)
        self.buttonBox.setGeometry(QtCore.QRect(10, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.txtUsager = QtWidgets.QLineEdit(Fen1)
        self.txtUsager.setGeometry(QtCore.QRect(120, 70, 113, 20))
        self.txtUsager.setObjectName("txtUsager")
        self.txtMotPasse = QtWidgets.QLineEdit(Fen1)
        self.txtMotPasse.setGeometry(QtCore.QRect(120, 100, 113, 20))
        self.txtMotPasse.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtMotPasse.setObjectName("txtMotPasse")
        self.label = QtWidgets.QLabel(Fen1)
        self.label.setGeometry(QtCore.QRect(60, 70, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Fen1)
        self.label_2.setGeometry(QtCore.QRect(36, 100, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Fen1)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 47, 13))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Fen1)
        self.buttonBox.accepted.connect(Fen1.accept)
        self.buttonBox.rejected.connect(Fen1.reject)
        QtCore.QMetaObject.connectSlotsByName(Fen1)

    def retranslateUi(self, Fen1):
        _translate = QtCore.QCoreApplication.translate
        Fen1.setWindowTitle(_translate("Fen1", "Dialog"))
        self.label.setText(_translate("Fen1", "Usager"))
        self.label_2.setText(_translate("Fen1", "Mot de passe"))
        self.label_3.setText(_translate("Fen1", "Fen1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fen1 = QtWidgets.QDialog()
    ui = Ui_Fen1()
    ui.setupUi(Fen1)
    Fen1.show()
    sys.exit(app.exec_())
